on:
  push:  # NOTE: All branches (but checks concurrency)
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

name: Test

jobs:
  functional:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ApeWorX/github-action@fix/pyproject-toml-support
    - run: ape compile --size
    - run: ape test -s --gas
